#pragma once

#include <cstdint>
#include <string_view>

namespace js::bytecode {

enum class OpCode : std::uint8_t {
    constant,
    undefined,
    get_local,
    set_local,
    initialize_local,
    reset_local,
    clone_local_binding,
    get_upvalue,
    get_module,
    get_name,
    get_name_or_undefined,
    get_this,
    get_argument,
    rest_arguments,
    set_upvalue,
    set_module,
    set_name,
    set_name_strict,
    closure,
    new_object,
    new_array,
    append_element,
    append_hole,
    append_spread,
    enumerate_keys,
    get_iterator,
    iterator_next,
    iterator_complete,
    iterator_value,
    to_object,
    copy_object_rest,
    copy_data_properties,
    define_property,
    define_element,
    define_getter,
    define_getter_element,
    get_property,
    set_property,
    set_property_strict,
    get_element,
    get_element_reference,
    set_element,
    set_element_strict,
    pop,
    add,
    subtract,
    multiply,
    divide,
    remainder,
    exponentiate,
    less,
    less_equal,
    greater,
    greater_equal,
    equal,
    not_equal,
    strict_equal,
    strict_not_equal,
    bitwise_and,
    bitwise_or,
    bitwise_xor,
    shift_left,
    shift_right,
    shift_right_unsigned,
    in_operator,
    instanceof_operator,
    negate,
    positive,
    logical_not,
    bitwise_not,
    typeof_,
    is_nullish,
    delete_property,
    delete_property_strict,
    delete_element,
    delete_element_strict,
    jump_if_false,
    jump,
    break_,
    continue_,
    call,
    construct,
    call_method,
    call_element,
    call_with_this,
    call_spread,
    construct_spread,
    call_method_spread,
    call_element_spread,
    call_with_this_spread,
    throw_,
    end_finally,
    yield_,
    return_,
    resolve_dynamic_ref, // u32 name constant, u32 fallback, u32 retained slot (bit 31 strict; low 31 bits: 0 none, 1..locals, then upvalues)
    get_dynamic_ref,     // u32 retained slot
    put_dynamic_ref,     // u32 retained slot; preserve top-of-stack RHS value
    delete_dynamic_ref,  // u32 retained slot; push boolean
    release_dynamic_ref, // u32 retained slot
};

[[nodiscard]] std::string_view opcode_name(OpCode opcode) noexcept;

} // namespace js::bytecode
